# Generated by Django 5.0.1 on 2024-01-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_order_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='wine',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wine',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
